version: '3.7'
services:
  sync:
    depends_on:
      - auth
      - postgres
      - provd
      - rabbitmq
      - sysconfd
      - confd
      - ari
    environment:
      TARGETS: "ari:5039,postgres:5432,rabbitmq:5672,provd:8666,sysconfd:8668,auth:9497,confd:9486"

  postgres:
    command: "-c 'log_min_duration_statement=0'"

  ari:
    image: wazoplatform/flask
    ports:
      - "5039"
    volumes:
      - "./mocks/ari.py:/tmp/ari.py"
    command: "python /tmp/ari.py 5039"

